### ISSUE TITLE
Fix Iron Gear recipe

### ISSUE THREAD

**Issue by FireBall1725** [FireBall1725/FirePack-1.12.2#1]
Iron gear conflicts with the iron frame

Iron Gear: <thermalfoundation:material:24>
Iron Frame: <advgenerators:iron_frame>

**Comment by dhtdesign** [comment]
I made a script for Advanced Generators to change the Iron Frame recipe and some other recipes.

Change:
Iron Frame
Turbine Rotors use previous tier to craft (Iron > Steel > Enderium & Manyullyn)
Removed:
Gold & Bronze Turbine

[Advanced Generators.zs](https://gist.github.com/dhtdesign/92c035a91c63a68e72882442e3bc5496)

**Comment by FireBall1725** [comment]
@dhtdesign pack v0.1.1 added the Advanced Generators.zs, however it disabled generators that SilentSean wanted to use, so I ended up disabling the script in the next pack.

Will add the previous tier script, but gold and bronze should also still be a thing i think.

**Comment by FireBall1725** [comment]
Completed
