### ISSUE TITLE
Update Flux Networks to fix crash

### ISSUE THREAD

**Issue by SeanLatimer** [FireBall1725/FirePack-1.12.2#14]
Update to the `4.0.10` where the crash we encountered should now be fixed
https://www.curseforge.com/minecraft/mc-mods/flux-networks/files/2792153

> Use 4.0.10

_Originally posted by @BloCamLimb in https://github.com/SonarSonic/Flux-Networks/issues/318#issuecomment-534067673_

**Comment by FireBall1725** [comment]
Updated
