### ISSUE TITLE
OpenComputers addons

### ISSUE THREAD

**Issue by SeanLatimer** [FireBall1725/FirePack-1.12.2#21]
At present, OC XNet Driver is the only way for 1.12.2 that would allow us to transfer items using OpenComputers.
https://www.curseforge.com/minecraft/mc-mods/oc-xnet-driver

This one looks interesting
https://www.curseforge.com/minecraft/mc-mods/openscreens

**Comment by FireBall1725** [comment]
OC Xnet Driver already in the pack, added Openscreens
