### ISSUE TITLE
Recipe Conflict between Stone Bucket & Stone Bowl

### ISSUE THREAD

**Issue by SeanLatimer** [FireBall1725/FirePack-1.12.2#22]
There is currently a recipe conflict between the stone bucket from Tinker's Compliment & Stone Bowl from Wireless Redstone. The bucket won, meaning we cannot craft some Wireless Redstone items at the moment.
![recipe](https://user-images.githubusercontent.com/11656396/65603021-cf75b200-df9c-11e9-96e8-7bb0f09ca97e.png)

**Comment by FireBall1725** [comment]
Complete
