### ISSUE TITLE
Classic Bar Mod

### ISSUE THREAD

**Issue by dhtdesign** [FireBall1725/FirePack-1.12.2#4]
![image](https://user-images.githubusercontent.com/7946125/65348595-dd64b500-dbe1-11e9-95a8-e1e4f6155432.png)

https://www.curseforge.com/minecraft/mc-mods/classic-bars

**Comment by SeanLatimer** [comment]
This mod is client only, so could be added after downloading the pack. Chaning those bars is opinionated imo & I know I'd be disabling that mod right away.

**Comment by FireBall1725** [comment]
Added, @SeanLatimer since it is client side it is easy for people to disable
